ensemble1:
  checkpoint_folder: "/home/joe/Documents/safealts/robomimic/bc_trained_models/varied_ic_3obj_300traj/20240725232820"
  checkpoint: "model_epoch_20.pth"
ensemble2:

ensemble3:

ensemble4:

ensemble5:
